# Generated by Django 3.1.2 on 2020-11-25 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
