# Generated by Django 3.1.2 on 2020-12-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201125_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='salesman_emailid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
